In [1]:
import pandas as pd

# Reading the CSV file
data = pd.read_csv("../datasets/employees.csv")
data.head()

      Name  Age Department  Salary
0    Alice   25         HR   50000
1      Bob   30         IT   60000
2  Charlie   28    Finance   55000
3    David   35  Marketing   70000
4      Eve   22         IT   48000

In [2]:
# dataset info
data.info()

<class 'pandas.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Name        5 non-null      str
 1   Age         5 non-null      int64
 2   Department  5 non-null      str
 3   Salary      5 non-null      int64
dtypes: int64(2), str(2)
memory usage: 292.0 bytes

In [3]:
# summary statistics of numeric columns
data.describe()

             Age        Salary
count   5.000000      5.000000
mean   28.000000  56600.000000
std     4.949747   8820.430828
min    22.000000  48000.000000
25%    25.000000  50000.000000
50%    28.000000  55000.000000
75%    30.000000  60000.000000
max    35.000000  70000.000000

In [4]:
# filtering rows where age is greater than 25
filter_data = data[data["age"] > 25]
filter_data

KeyError: 'age'